[package]
name = "py-diffsol-new"
version = "0.1.0"
edition = "2021"

[lib]
name = "py_diffsol_new"
crate-type = ["cdylib"]

[dependencies]
diffsol = { version = "0.5.3", features = ["diffsl"] }
faer = "0.21.9"
nalgebra = "0.33.2"
numpy = "0.24.0"
pyo3 = "0.24.0"
