[package]
name = "py-diffsol-new"
version = "0.1.0"
edition = "2021"

[lib]
name = "py_diffsol_new"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", default-features = false, features = ["extension-module"] }
diffsol = { version = "0.6.6", features = ["diffsl", "diffsl-llvm", "nalgebra", "faer"] }
nalgebra = { version = ">=0.30, <0.34", default-features = false, features = ["std"] }
faer = "0.22.6"
numpy = "0.25.0"

[dev-dependencies]
pyo3 = { version = "*", features = ["auto-initialize"] }
